name: Test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tsc:
    name: Run tsc
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tsc
        run: npm run build
